In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.15.4


In [4]:
arr = np.arange(10)
print(arr)
arr

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.full(3,3)

array([3, 3, 3])

In [8]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [12]:
arr[arr % 2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
out = arr
out[out % 2 ==1] = -1
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
#out = arr
#out[out % 2 == 1] = -1


In [25]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

c = np.concatenate([a,b], axis=0)

In [33]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [38]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [43]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [2]:
import numpy as np
a = np.array([1,2,2,3,4,3,4,5,6,3,4])
b = np.array([7,2,10,2,4,9,4,9,8.5,3])

In [3]:
np.intersect1d(a,b)

array([2., 3., 4.])

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [6]:
c = np.intersect1d(a,b)

In [7]:
c


array([5])

In [8]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [12]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [13]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [16]:
index = np.where((a>5) & (a<10))

In [17]:
a[index]

array([6, 9])

In [19]:
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[float])
    

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [22]:
pair_max(a,b)

array([ 7.,  2., 10.,  2.,  7.,  4.,  9.,  4.,  9.,  8.])

In [24]:
#Swap columns 1 and 2 in the array arr.

In [25]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[[2,1,0], :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [30]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [31]:
#Reverse the rows of a 2D array arr.

In [37]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [38]:
arr[::,-1]

array([2, 5, 8])

In [43]:
arr[-1,::]

array([6, 7, 8])

In [42]:
arr[0,::]

array([0, 1, 2])

In [44]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [45]:
rand_arr = np.random.uniform(5,10, size=(5,3))

In [46]:
rand_arr

array([[7.87937521, 6.68793146, 9.95549461],
       [8.60819882, 7.44150904, 5.45016753],
       [8.35841733, 6.44473569, 8.45719152],
       [7.17642205, 7.17671457, 8.25275526],
       [5.34157815, 6.37857858, 8.00897591]])

In [57]:
rand_arr[:,:3]

array([[7.87937521, 6.68793146, 9.95549461],
       [8.60819882, 7.44150904, 5.45016753],
       [8.35841733, 6.44473569, 8.45719152],
       [7.17642205, 7.17671457, 8.25275526],
       [5.34157815, 6.37857858, 8.00897591]])

In [58]:
np.set_printoptions(precision=3)

In [59]:
rand_arr

array([[7.879, 6.688, 9.955],
       [8.608, 7.442, 5.45 ],
       [8.358, 6.445, 8.457],
       [7.176, 7.177, 8.253],
       [5.342, 6.379, 8.009]])

In [61]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [62]:
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [63]:
np.set_printoptions(suppress=True, precision=6)

In [64]:
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [65]:
a = np.arange(15)

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
np.set_printoptions(threshold=6)

In [68]:
a 

array([ 0,  1,  2, ..., 12, 13, 14])

In [69]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [75]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [77]:
print(iris.shape)

(150, 5)


In [84]:
species = np.array([column[4] for column in iris])

In [86]:
species[:]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S15')